name: Push
on: [push]
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          target=/usr/local/bin/ktlint; 
          sudo wget -q -O $target https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint && 
          sudo chmod a+x $target
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - run: task ktlint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/build-cache 
            ~/.android/cache
          key: android-build-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            android-build-${{ github.sha }}-
            android-build-
      - name: Chmod gradlew
        run: chmod a+x ./gradlew
      - name: Download dependencies
        run: ./gradlew androidDependencies
      - name: Run build
        run: ./gradlew build
