name: Push
on: [push]
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          target=/usr/local/bin/ktlint; 
          sudo wget -q -O $target https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint && 
          sudo chmod a+x $target
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - run: task ktlint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle dist
        uses: actions/cache@v2
        with:
          key: dists-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          path: ~/.gradle/wrapper/dists
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ github.sha }}
          restore-keys: |
            gradle-
      - name: Chmod gradlew
        run: chmod a+x ./gradlew
      - name: Download dependencies
        run: ./gradlew androidDependencies
      - name: Run build, lint and test
        run: ./gradlew build lint test
      - uses: actions/upload-artifact@v2
        with:
          name: apk-outputs
          path: 'app/build/outputs/apk'
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: '*/build/reports'
